### ISSUE TITLE
Where can I download the dataset: BCICIV_1calib_1000Hz.mat ?

### ISSUE THREAD

**Issue by gittanzhao** [rahul2227/Optimized-BCI#1]
Where can I download the dataset: BCICIV_1calib_1000Hz.mat ?  Can you share one with me? email:993317238@qq.com

**Comment by rahul2227** [comment]
Hey @gittanzhao, 
You can find and download the datasets on this [link](https://www.bbci.de/competition/iv/). I used the "Dataset-1".
